name: cat_app
description: Cat application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dio: ^4.0.6
  equatable: ^2.0.3
  formz: ^0.4.1
  freezed: ^2.1.0+1
  flutter_svg: ^1.1.1+1
  flutter_keyboard_visibility: ^5.3.0
  overlay_support: ^2.0.1
  get_it: ^7.2.0
  retrofit: ^3.0.1+1
  json_annotation: ^4.6.0
  dartz: ^0.10.1
  infinite_scroll_pagination: ^3.2.0
  flutter_secure_storage: ^5.0.2
  cached_network_image: ^3.2.1
  flutter_native_splash: ^2.2.7

dev_dependencies:
  json_serializable: ^6.3.1
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.1.6
  retrofit_generator: ^4.0.3
  flutter_launcher_icons: ^0.9.3




flutter_gen:
  output: lib/core/generated/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/i18n/
    - assets/images/

flutter_native_splash:
  color: "#5068a9"
  background_image: "assets/images/app_logo.png"
  fullscreen: true
  android_12:
    image:  "assets/images/app_logo.png"
    icon_background_color: "#ffffff"

  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo_rounded.png"